version: '3.7'

services:
  test-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/node/app/src
    container_name: test-backend
    ports:
      - '3001:3001'
    command: npm run dev